# Generated by Django 5.2.16 on 2026-08-02 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocrrecord',
            name='status',
            field=models.CharField(choices=[('uploading', 'Uploading'), ('loading_model', 'Loading Model'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='uploading', max_length=20),
        ),
        migrations.AlterField(
            model_name='ocrrecord',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
