# Generated by Django 5.2.16 on 2026-08-02 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_api', '0002_ocrrecord_status_alter_ocrrecord_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocrrecord',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ocrrecord',
            name='status',
            field=models.CharField(choices=[('uploading', 'Uploading'), ('loading_model', 'Loading Model'), ('processing', 'Processing'), ('segmenting_lines', 'Segmenting image into lines'), ('processing_lines', 'Recognizing lines'), ('completed', 'Completed'), ('failed', 'Failed')], default='uploading', max_length=20),
        ),
    ]
