# Generated by Django 5.2.16 on 2026-08-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_api', '0003_ocrrecord_error_message_alter_ocrrecord_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocrrecord',
            name='document_type',
            field=models.CharField(
                choices=[('page', 'Page'), ('table', 'Table')],
                default='page',
                max_length=10,
            ),
        ),
    ]
