# Generated by Django 5.2.16 on 2026-08-14 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_api', '0005_ocrrecord_file_name_ocrrecord_file_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocrrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
