# Generated by Django 5.2.16 on 2026-08-17 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_api', '0007_editedocrexample'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='generated_storage_used',
            field=models.BigIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='GeneratedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, max_length=1024, upload_to='generated_files/%Y/%m/')),
                ('file_type', models.CharField(choices=[('PDF', 'PDF'), ('JSON', 'JSON'), ('WORD', 'Word'), ('EXCEL', 'Excel')], max_length=16)),
                ('mime_type', models.CharField(max_length=128)),
                ('file_size_bytes', models.BigIntegerField(default=0)),
                ('storage_backend', models.CharField(choices=[('local', 'Local'), ('s3', 'S3')], default='local', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_files', to='ocr_api.ocrrecord')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'generated_files',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='generatedfile',
            constraint=models.UniqueConstraint(fields=('source_image', 'file_type'), name='uq_generated_file_source_type'),
        ),
        migrations.AddConstraint(
            model_name='generatedfile',
            constraint=models.CheckConstraint(condition=models.Q(('file_type__in', ['PDF', 'JSON', 'WORD', 'EXCEL'])), name='ck_generated_file_type'),
        ),
        migrations.AddConstraint(
            model_name='generatedfile',
            constraint=models.CheckConstraint(condition=models.Q(('file_size_bytes__gte', 0)), name='ck_generated_file_size_non_negative'),
        ),
        migrations.AddIndex(
            model_name='generatedfile',
            index=models.Index(fields=['user', '-created_at'], name='idx_gf_user_created'),
        ),
        migrations.AddIndex(
            model_name='generatedfile',
            index=models.Index(fields=['user', 'file_type'], name='idx_gf_user_type'),
        ),
        migrations.AddIndex(
            model_name='generatedfile',
            index=models.Index(fields=['source_image'], name='idx_gf_source'),
        ),
        migrations.AddIndex(
            model_name='generatedfile',
            index=models.Index(fields=['user', 'file_type', '-created_at'], name='idx_gf_user_type_created'),
        ),
    ]
